import type { Metadata } from "next";
import { Geist_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <footer className="border-t-4 border-[#111111] bg-[#111111] px-6 py-8 text-[#f4f0e8] sm:px-8 lg:px-12">
          <div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-xl font-black uppercase tracking-[-0.06em]">
                kelana<span className="text-[#ff5c35]">.</span>
              </p>
              <p className="mt-2 text-xs font-bold uppercase tracking-widest text-[#bdb9ad]">
                © 2026 KelanaAI
              </p>
            </div>

            <nav aria-label="Social links" className="flex flex-wrap gap-3">
              <a
                href="https://instagram.com"
                target="_blank"
                rel="noreferrer"
                className="border-2 border-[#f4f0e8] px-4 py-2 text-xs font-black uppercase transition hover:bg-[#f5d547] hover:text-[#111111]"
              >
                Instagram
              </a>
              <a
                href="https://github.com"
                target="_blank"
                rel="noreferrer"
                className="border-2 border-[#f4f0e8] px-4 py-2 text-xs font-black uppercase transition hover:bg-[#ff5c35] hover:text-[#111111]"
              >
                GitHub
              </a>
              <a
                href="mailto:hello@kelana.ai"
                className="border-2 border-[#f4f0e8] px-4 py-2 text-xs font-black uppercase transition hover:bg-[#f5d547] hover:text-[#111111]"
              >
                Email
              </a>
            </nav>
          </div>
        </footer>
      </body>
    </html>
  );
}
